### ISSUE TITLE
Issue reading oneplus nord

### ISSUE THREAD

**Issue by jojoosinga** [Beliathal/QFILHelper#1]
[port_trace.txt](https://github.com/Beliathal/QFILHelper/files/12160666/port_trace.txt)

This is my error, the device in question is fucked pretty hard. No partitions anymore I think

**Comment by Beliathal** [comment]
This app was never meant to work with OnePlus devices. The GPT version was tuned to work specifically with LG phones and it expects certain partition layout, that OnePlus might or might not have. While earlier, non-GPT versions, could work in theory with OnePlus, but they've never been tested with anything but LG phones.
