### ISSUE TITLE
Remove Persist, Persist_LG, and Persdata in the restore all partition option.

### ISSUE THREAD

**Issue by roy-heinrich** [Beliathal/QFILHelper#11]
These files here will f*ck up the TEE of an LG device if restored. Now the device won't be Play Certified even if you lock the bootloader and will only pass Basic Integrity, always.

**Comment by Beliathal** [comment]
The app would only restore those partitions that the user chooses to put in the flash folder, whether the user wants to restore Persist, Persist_LG, and Persdata or not - is their own business. I don't think that the app should restrict the user in any way, imho. 

That being said, I'm working on a new GUI for this app and it'll have a warning Window if and when it detects that the user is about to flash those partitions.

Thank you kindly!
