### ISSUE TITLE
possible to release the latest source code

### ISSUE THREAD

**Issue by qiurigao** [Beliathal/QFILHelper#2]
Thanks for the masterpiece, I need to translate to Chinese, is it possible to release the latest source code, the current version stuck at 1.0.0.569

**Comment by qiurigao** [comment]
QFILHelper_GPT_Edition opencode ？

**Comment by Beliathal** [comment]
Yes friend, it's open source, however, GPT edition was/is in beta stage. I simply didn't get enough feedback from people to decide if it was stable enough to be released. Since people weren't interested in this version, I didn't bother to upload the code. If you still need it, I'll upload as soon as I get to my work office.

**Comment by qiurigao** [comment]
> 是的，朋友，它是开源的，但是，GPT 版本处于测试阶段。我只是没有从人们那里得到足够的反馈来决定它是否足够稳定，可以发布。由于人们对这个版本不感兴趣，所以我懒得上传代码。如果您仍然需要它，我会在到达工作办公室后立即上传。



> Yes friend, it's open source, however, GPT edition was/is in beta stage. I simply didn't get enough feedback from people to decide if it was stable enough to be released. Since people weren't interested in this version, I didn't bother to upload the code. If you still need it, I'll upload as soon as I get to my work office.

Ok, thank you very much for your work. You can upload to the beta branch without destroying the main branch. In addition, how to add localized language files, it seems that only English?

**Comment by Beliathal** [comment]
You're most welcome. 

To add Chinese language, there are 2 possible ways: 

1: You can replace English or Russian with Chinese.
2: You can add Chinese as third language language. 

The language files are located in Resources folder. 

1. If you wish to simply replace English with Chinese: 
Open menu_en.txt and msg_en.txt and translate the text inside those files to Chinese. 

2. If you wish to keep English and Russian, and add Chinese as a third language: 
- You'll need to modify the code inside clsMsg.vb
- Create menu_ch.txt and msg_ch.txt 
- Add menu_ch.txt and msg_ch.txt to the Project Resources.

**Comment by qiurigao** [comment]
Is there any way to get the current system language environment and then automatically select the language?The automatic selection language code I added does not take effect.

**Comment by Beliathal** [comment]
The app uses command line arguments for switching language, the code is also located in clsMsg.vb. It's a more simpler solution than using system language environment (in my opinion). But to answer you question: yes it is possible.

**Comment by qiurigao** [comment]
Whether you can provide the extraction method of partition table and parsing code. Vb.net I don't quite understand, or other language codes.

**Comment by Beliathal** [comment]
Sorry for delayed reply. 

I've updated the GTP Edition with your translation, compiled it and added to the releases section. To switch the app to Chinese, run it with command line arguments as follows:  qfilhelper.exe -advanced -NTFS -zh -utf8. 

To test the code in Visual Studio, you can add/change command line parameters in Debug menu -> QFIL Properties -> Start Options.

The extraction of GPT partition table info is done inside the function LoadGPTData in class clsParts.vb. I've relied on this article on [wikipedia](https://en.wikipedia.org/wiki/GUID_Partition_Table) to help me build the GPT headers extraction code.
