### ISSUE TITLE
Can backup be shared among devices of the same model?

### ISSUE THREAD

**Issue by robertruen1980** [Beliathal/QFILHelper#9]
Hi! Two devices of the same model have different system versions. One of them, with a lower version, has been fully backed up using QFILHELPER. Can the other device with a higher version be downgraded by flashing this backup? I tried this method but couldn't boot successfully. Please advise if I should avoid flashing certain partitions?

**Comment by Beliathal** [comment]
Yes, you can use my app to downgrade android versions, flash partitions from one phone to another and cross-flash firmware from different regions. That being said, it all depends on your device model, partition layout and android version. Generally speaking, you'd want to start with these partitions: product, system, op, vendor, boot. If the device doesn't boot, try also (one at a time): abl, raw_resources, laf, xbl, xbl_config, modem, ftm, modemst1, modemst2, fsg, fsc, sid. You'd get more detailed help on the matter if you head over to xda forums.
